// This test was auto-generated by Playwright Codegen
// Command: npx playwright codegen https://the-internet.herokuapp.com/dropdown
const { test, expect } = require('@playwright/test');

test('Dropdown selection - recorded via codegen', async ({ page }) => {
  await page.goto('https://the-internet.herokuapp.com/dropdown');
  await page.locator('#dropdown').selectOption('2');
  await expect(page.locator('#dropdown')).toHaveValue('2');
});
