// This test was auto-generated by Playwright Codegen
// Command: npx playwright codegen https://the-internet.herokuapp.com/login
const { test, expect } = require('@playwright/test');

test('Login flow - recorded via codegen', async ({ page }) => {
  await page.goto('https://the-internet.herokuapp.com/login');
  await page.locator('#username').click();
  await page.locator('#username').fill('tomsmith');
  await page.locator('#password').click();
  await page.locator('#password').fill('SuperSecretPassword!');
  await page.getByRole('button', { name: ' Login' }).click();
  await expect(page.locator('#flash')).toContainText('You logged into a secure area!');
});
