#!/usr/bin/env node
/**
 * Slack Message Formatter
 * Formats test results as Slack-compatible markdown
 */

const fs = require('fs');
const path = require('path');
const { analyzeResults } = require('./analyze_results');

const GREEN = '\x1b[32m';
const CYAN = '\x1b[36m';
const YELLOW = '\x1b[33m';
const RED = '\x1b[31m';
const BOLD = '\x1b[1m';
const DIM = '\x1b[2m';
const RESET = '\x1b[0m';

function main() {
  console.log(`\n${CYAN}╔═══════════════════════════════════════════════════════════════╗${RESET}`);
  console.log(`${CYAN}║          ${BOLD}Slack Message Formatter${RESET}${CYAN}                             ║${RESET}`);
  console.log(`${CYAN}╚═══════════════════════════════════════════════════════════════╝${RESET}\n`);

  const resultsPath = path.join(__dirname, 'sample_results.json');
  const analysis = analyzeResults(resultsPath);

  const riskEmoji = analysis.risk.level === 'LOW' ? ':white_check_mark:' : analysis.risk.level === 'MEDIUM' ? ':warning:' : ':rotating_light:';
  const statusEmoji = analysis.summary.failed === 0 ? ':tada:' : ':x:';

  let message = `${statusEmoji} *Test Execution Report*\n`;
  message += `_${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}_\n\n`;

  message += `*Summary*\n`;
  message += `| Metric | Value |\n`;
  message += `|--------|-------|\n`;
  message += `| Total Tests | ${analysis.summary.total} |\n`;
  message += `| :white_check_mark: Passed | ${analysis.summary.passed} |\n`;
  message += `| :x: Failed | ${analysis.summary.failed} |\n`;
  message += `| Pass Rate | ${analysis.summary.passRate}% |\n`;
  message += `| Duration | ${(analysis.summary.totalDuration / 1000).toFixed(1)}s |\n`;
  message += `| Risk | ${riskEmoji} ${analysis.risk.level} |\n\n`;

  if (analysis.summary.failed > 0) {
    message += `*:x: Failed Tests*\n`;
    for (const test of analysis.failedTests) {
      const error = test.errors[0]?.message?.split('\n')[0] || 'Unknown';
      message += `> :red_circle: *${test.title}*\n`;
      message += `> _${error.substring(0, 100)}_\n\n`;
    }

    message += `*Failure Categories*\n`;
    for (const [category, tests] of Object.entries(analysis.failureCategories)) {
      message += `- \`${category}\`: ${tests.length} failure(s)\n`;
    }
    message += '\n';
  }

  message += `---\n_Generated by AI Smart Test Reporter_`;

  // Save to file
  const reportsDir = path.join(__dirname, 'reports');
  if (!fs.existsSync(reportsDir)) fs.mkdirSync(reportsDir, { recursive: true });

  const slackPath = path.join(reportsDir, 'slack_message.md');
  fs.writeFileSync(slackPath, message);

  // Console output
  console.log(`${BOLD}Slack Message Preview:${RESET}\n`);
  console.log(message.replace(/:white_check_mark:/g, '✅').replace(/:x:/g, '❌').replace(/:warning:/g, '⚠️').replace(/:rotating_light:/g, '🚨').replace(/:tada:/g, '🎉').replace(/:red_circle:/g, '🔴'));
  console.log(`\n${CYAN}  📄 Saved to: ${slackPath}${RESET}\n`);
}

main();
